/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsFormRouteImport } from './routes/docs/form'
import { Route as DocsDataTableRouteImport } from './routes/docs/data-table'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsFormRoute = DocsFormRouteImport.update({
  id: '/docs/form',
  path: '/docs/form',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsDataTableRoute = DocsDataTableRouteImport.update({
  id: '/docs/data-table',
  path: '/docs/data-table',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs/data-table': typeof DocsDataTableRoute
  '/docs/form': typeof DocsFormRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs/data-table': typeof DocsDataTableRoute
  '/docs/form': typeof DocsFormRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs/data-table': typeof DocsDataTableRoute
  '/docs/form': typeof DocsFormRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/docs/data-table' | '/docs/form'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/docs/data-table' | '/docs/form'
  id: '__root__' | '/' | '/docs/data-table' | '/docs/form'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsDataTableRoute: typeof DocsDataTableRoute
  DocsFormRoute: typeof DocsFormRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/form': {
      id: '/docs/form'
      path: '/docs/form'
      fullPath: '/docs/form'
      preLoaderRoute: typeof DocsFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/data-table': {
      id: '/docs/data-table'
      path: '/docs/data-table'
      fullPath: '/docs/data-table'
      preLoaderRoute: typeof DocsDataTableRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsDataTableRoute: DocsDataTableRoute,
  DocsFormRoute: DocsFormRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
