/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsChar123SlugChar125RouteImport } from './routes/docs.{-$slug}'
import { Route as DocsDeveloperSetupRouteImport } from './routes/docs/developer-setup'
import { Route as DocsSitesTemplateRouteImport } from './routes/docs/sites/template'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsChar123SlugChar125Route = DocsChar123SlugChar125RouteImport.update({
  id: '/docs/{-$slug}',
  path: '/docs/{-$slug}',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsDeveloperSetupRoute = DocsDeveloperSetupRouteImport.update({
  id: '/docs/developer-setup',
  path: '/docs/developer-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSitesTemplateRoute = DocsSitesTemplateRouteImport.update({
  id: '/docs/sites/template',
  path: '/docs/sites/template',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs/developer-setup': typeof DocsDeveloperSetupRoute
  '/docs/{-$slug}': typeof DocsChar123SlugChar125Route
  '/docs/sites/template': typeof DocsSitesTemplateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs/developer-setup': typeof DocsDeveloperSetupRoute
  '/docs/{-$slug}': typeof DocsChar123SlugChar125Route
  '/docs/sites/template': typeof DocsSitesTemplateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs/developer-setup': typeof DocsDeveloperSetupRoute
  '/docs/{-$slug}': typeof DocsChar123SlugChar125Route
  '/docs/sites/template': typeof DocsSitesTemplateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs/developer-setup'
    | '/docs/{-$slug}'
    | '/docs/sites/template'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/docs/developer-setup' | '/docs/{-$slug}' | '/docs/sites/template'
  id:
    | '__root__'
    | '/'
    | '/docs/developer-setup'
    | '/docs/{-$slug}'
    | '/docs/sites/template'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsDeveloperSetupRoute: typeof DocsDeveloperSetupRoute
  DocsChar123SlugChar125Route: typeof DocsChar123SlugChar125Route
  DocsSitesTemplateRoute: typeof DocsSitesTemplateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/{-$slug}': {
      id: '/docs/{-$slug}'
      path: '/docs/{-$slug}'
      fullPath: '/docs/{-$slug}'
      preLoaderRoute: typeof DocsChar123SlugChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/developer-setup': {
      id: '/docs/developer-setup'
      path: '/docs/developer-setup'
      fullPath: '/docs/developer-setup'
      preLoaderRoute: typeof DocsDeveloperSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/sites/template': {
      id: '/docs/sites/template'
      path: '/docs/sites/template'
      fullPath: '/docs/sites/template'
      preLoaderRoute: typeof DocsSitesTemplateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsDeveloperSetupRoute: DocsDeveloperSetupRoute,
  DocsChar123SlugChar125Route: DocsChar123SlugChar125Route,
  DocsSitesTemplateRoute: DocsSitesTemplateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
